// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj_s4kzqb0iEx6RXjBR33-YkqMAIcZLhM',
    appId: '1:882099140446:web:a12aea45170a821b9901cf',
    messagingSenderId: '882099140446',
    projectId: 'tools-hub-4c4a1',
    authDomain: 'www.aiworkx.space',
    storageBucket: 'tools-hub-4c4a1.firebasestorage.app',
    measurementId: 'G-L0Z7ZX0692',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjOhQWmz69EPIJ30bVjTwsEc-iRR0Uv38',
    appId: '1:882099140446:android:4f95b800e8e0bfe69901cf',
    messagingSenderId: '882099140446',
    projectId: 'tools-hub-4c4a1',
    storageBucket: 'tools-hub-4c4a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXfvOLeiN3ymMa5tBn4Nr1jDQ61O9CRC8',
    appId: '1:882099140446:ios:a8c9623af432795e9901cf',
    messagingSenderId: '882099140446',
    projectId: 'tools-hub-4c4a1',
    storageBucket: 'tools-hub-4c4a1.firebasestorage.app',
    iosBundleId: 'com.example.toolshub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXfvOLeiN3ymMa5tBn4Nr1jDQ61O9CRC8',
    appId: '1:882099140446:ios:a8c9623af432795e9901cf',
    messagingSenderId: '882099140446',
    projectId: 'tools-hub-4c4a1',
    storageBucket: 'tools-hub-4c4a1.firebasestorage.app',
    iosBundleId: 'com.example.toolshub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCj_s4kzqb0iEx6RXjBR33-YkqMAIcZLhM',
    appId: '1:882099140446:web:91ec68e597a75f989901cf',
    messagingSenderId: '882099140446',
    projectId: 'tools-hub-4c4a1',
    authDomain: 'www.aiworkx.space',
    storageBucket: 'tools-hub-4c4a1.firebasestorage.app',
    measurementId: 'G-GJEXN21FZQ',
  );
}
